set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U7 [get_ports {display_floor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[0]}]
set_property PACKAGE_PIN V5 [get_ports {display_floor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[1]}]
set_property PACKAGE_PIN U5 [get_ports {display_floor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[2]}]
set_property PACKAGE_PIN V8 [get_ports {display_floor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[3]}]
set_property PACKAGE_PIN U8 [get_ports {display_floor[4]}]
set_property PACKAGE_PIN W6 [get_ports {display_floor[5]}]
set_property PACKAGE_PIN W7 [get_ports {display_floor[6]}]
set_property PACKAGE_PIN U2 [get_ports {display_floor[7]}]
set_property PACKAGE_PIN U4 [get_ports {display_floor[8]}]
set_property PACKAGE_PIN V4 [get_ports {display_floor[9]}]
set_property PACKAGE_PIN W4 [get_ports {display_floor[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_floor[10]}]


set_property PACKAGE_PIN T18 [get_ports floor1_btn]
set_property PACKAGE_PIN L1 [get_ports floor1_led]
set_property PACKAGE_PIN W19 [get_ports floor2_btn]
set_property PACKAGE_PIN P1 [get_ports floor2_led]
set_property PACKAGE_PIN U18 [get_ports floor3_btn]
set_property PACKAGE_PIN N3 [get_ports floor3_led]
set_property PACKAGE_PIN T17 [get_ports floor4_btn]
set_property PACKAGE_PIN P3 [get_ports floor4_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor1_btn]
set_property IOSTANDARD LVCMOS33 [get_ports floor1_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor2_btn]
set_property IOSTANDARD LVCMOS33 [get_ports floor2_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor3_btn]
set_property IOSTANDARD LVCMOS33 [get_ports floor3_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor4_btn]
set_property IOSTANDARD LVCMOS33 [get_ports floor4_led]

set_property IOSTANDARD LVCMOS33 [get_ports door_close_led]
set_property IOSTANDARD LVCMOS33 [get_ports door_close_sw]
set_property IOSTANDARD LVCMOS33 [get_ports door_open_led]
set_property IOSTANDARD LVCMOS33 [get_ports door_open_sw]
set_property PACKAGE_PIN U16 [get_ports door_close_led]
set_property PACKAGE_PIN V17 [get_ports door_close_sw]
set_property PACKAGE_PIN E19 [get_ports door_open_led]
set_property PACKAGE_PIN V16 [get_ports door_open_sw]


set_property IOSTANDARD LVCMOS33 [get_ports call_btn]
set_property IOSTANDARD LVCMOS33 [get_ports call_led2]
set_property IOSTANDARD LVCMOS33 [get_ports call_led1]
set_property PACKAGE_PIN U17 [get_ports call_btn]
set_property PACKAGE_PIN V19 [get_ports call_led1]
set_property PACKAGE_PIN U19 [get_ports call_led2]

set_property IOSTANDARD LVCMOS33 [get_ports out1_up_led]
set_property IOSTANDARD LVCMOS33 [get_ports out1_up_sw]
set_property IOSTANDARD LVCMOS33 [get_ports out2_down_led]
set_property IOSTANDARD LVCMOS33 [get_ports out2_down_sw]
set_property IOSTANDARD LVCMOS33 [get_ports out2_up_led]
set_property IOSTANDARD LVCMOS33 [get_ports out2_up_sw]
set_property IOSTANDARD LVCMOS33 [get_ports out3_down_led]
set_property IOSTANDARD LVCMOS33 [get_ports out3_down_sw]
set_property IOSTANDARD LVCMOS33 [get_ports out3_up_led]
set_property IOSTANDARD LVCMOS33 [get_ports out3_up_sw]
set_property IOSTANDARD LVCMOS33 [get_ports out4_down_led]
set_property IOSTANDARD LVCMOS33 [get_ports out4_down_sw]
set_property PACKAGE_PIN W3 [get_ports out1_up_led]
set_property PACKAGE_PIN T2 [get_ports out1_up_sw]
set_property PACKAGE_PIN V3 [get_ports out2_up_led]
set_property PACKAGE_PIN T3 [get_ports out2_up_sw]
set_property PACKAGE_PIN V13 [get_ports out2_down_led]
set_property PACKAGE_PIN V2 [get_ports out2_down_sw]
set_property PACKAGE_PIN W13 [get_ports out3_up_sw]
set_property PACKAGE_PIN V14 [get_ports out3_up_led]
set_property PACKAGE_PIN W14 [get_ports out3_down_sw]
set_property PACKAGE_PIN U14 [get_ports out3_down_led]
set_property PACKAGE_PIN V15 [get_ports out4_down_sw]
set_property PACKAGE_PIN U15 [get_ports out4_down_led]

set_property IOSTANDARD LVCMOS33 [get_ports led_out_test_sw]
set_property PACKAGE_PIN R3 [get_ports led_out_test_sw]
